# Generated by Django 5.2.1 on 2025-06-07 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='responsable_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_responsables', to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='configurationevaluationec',
            name='ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.ec'),
        ),
        migrations.AddField(
            model_name='ecclasse',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='ecclasse',
            name='ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.ec'),
        ),
        migrations.AddField(
            model_name='recapitulatifsemestriel',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='recapitulatifsemestriel',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='recapitulatifsemestriel',
            name='genere_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('numero',)},
        ),
        migrations.AddField(
            model_name='recapitulatifsemestriel',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semestre'),
        ),
        migrations.AddField(
            model_name='recapitulatifsemestriel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddField(
            model_name='configurationevaluationec',
            name='type_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.typeevaluation'),
        ),
        migrations.AddField(
            model_name='ue',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveau'),
        ),
        migrations.AddField(
            model_name='ue',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semestre'),
        ),
        migrations.AddField(
            model_name='ec',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_constitutifs', to='academics.ue'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('code', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='ecclasse',
            unique_together={('ec', 'classe')},
        ),
        migrations.AlterUniqueTogether(
            name='recapitulatifsemestriel',
            unique_together={('classe', 'semestre', 'session', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='configurationevaluationec',
            unique_together={('ec', 'type_evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='ue',
            unique_together={('code', 'niveau', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='ec',
            unique_together={('code', 'ue')},
        ),
    ]
