# Generated by Django 5.2.1 on 2025-06-07 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.enseignant'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='enseignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.enseignement'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='type_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.typeevaluation'),
        ),
        migrations.AddField(
            model_name='inscriptionec',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='inscriptionec',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='inscriptionec',
            name='ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.ec'),
        ),
        migrations.AddField(
            model_name='inscriptionec',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='moyenneec',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='moyenneec',
            name='ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.ec'),
        ),
        migrations.AddField(
            model_name='moyenneec',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='moyenneec',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddField(
            model_name='moyennesemestre',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='moyennesemestre',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='moyennesemestre',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='moyennesemestre',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semestre'),
        ),
        migrations.AddField(
            model_name='moyennesemestre',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddField(
            model_name='moyenneue',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='moyenneue',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='moyenneue',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AddField(
            model_name='moyenneue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.ue'),
        ),
        migrations.AddField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.etudiant'),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='note',
            name='modifiee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tacheautomatisee',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.anneeacademique'),
        ),
        migrations.AddField(
            model_name='tacheautomatisee',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classe'),
        ),
        migrations.AddField(
            model_name='tacheautomatisee',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semestre'),
        ),
        migrations.AddField(
            model_name='tacheautomatisee',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('enseignant', 'ec', 'classe', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionec',
            unique_together={('etudiant', 'ec', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='moyenneec',
            unique_together={('etudiant', 'ec', 'session', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='moyennesemestre',
            unique_together={('etudiant', 'classe', 'semestre', 'session', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='moyenneue',
            unique_together={('etudiant', 'ue', 'session', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'evaluation')},
        ),
    ]
