# Generated by Django 5.2.1 on 2025-06-01 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('duree_annees', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cycles',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'domaines',
            },
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('actif', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
            ],
            options={
                'db_table': 'types_formation',
                'unique_together': {('nom', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.domaine')),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typeformation')),
            ],
            options={
                'db_table': 'filieres',
                'unique_together': {('code', 'type_formation')},
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('credits_requis', models.PositiveIntegerField(default=60)),
                ('actif', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cycle')),
            ],
            options={
                'db_table': 'niveaux',
                'ordering': ['cycle', 'numero'],
                'unique_together': {('numero', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
            ],
            options={
                'db_table': 'options',
                'unique_together': {('code', 'filiere')},
            },
        ),
    ]
